# Page Title
page_title: Weekly Planner - Busy Mom

# App Info
ios_app_id: 1234793120
ios_app_country: us

appstore_link: # Will auto-populate if iOS App ID is correct
playstore_link: # Add Google Play Store link if available
presskit_download_link: https://alicsystems.com/presskit-busy-mom.zip

app_icon: assets/appicon.png
app_name: Weekly Planner - Busy Mom
app_price: Free with optional subscriptions
app_description: Gamified weekly planner designed for busy moms – plan, earn XP, unlock rewards & build habits.

enable_smart_app_banner: true

# Information About Yourself
your_name: Alic Systems
your_link: https://alicsystems.com
your_city: Lagos
email_address: support@alicsystems.com
linkedin_username: alicsystems
linkedin_company: alicsystems
facebook_username: alicsystems
instagram_username: alicsystems
twitter_username: alicsystems
github_username: alicsystems
youtube_username: alicsystems
mastodon_link: 

# Feature List
features:
  - title: Smart Planning System
    description: Simple weekly & daily layouts, mom-focused categories, and offline planning.
    fontawesome_icon_name: calendar-alt

  - title: Gamified Motivation
    description: Earn XP, unlock badges, and level up your "Mom Planner" status.
    fontawesome_icon_name: gamepad

  - title: Habit Building Tools
    description: Track routines, earn bonus XP for streaks, and build lasting habits.
    fontawesome_icon_name: tasks

  - title: Real-Time Progress
    description: Weekly dashboard with rewards, insights & confetti celebrations.
    fontawesome_icon_name: chart-line

  - title: Mom-Life Integration
    description: Pre-loaded templates, quick capture, and cross-device sync.
    fontawesome_icon_name: sync-alt

  - title: Affordable Subscriptions
    description: Pro Weekly – $4.99/week; Pro Yearly – $29.99/year. Cancel anytime.
    fontawesome_icon_name: dollar-sign

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black

body_background_color: "#ffffff"
link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

# Jekyll Configuration
sass:
  style: :compressed

exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

markdown: kramdown
